services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    environment:
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
