server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /submit {
        proxy_pass http://server:3000/submit;
        proxy_set_header Content-Type application/json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
